export const dataDashboardMediumAlerts = [
  {
    id: 'alert-1',
    text: '7 yêu cầu phê duyệt',
    emphasis: true,
    suffix: 'đang chờ xử lý',
  },
  {
    id: 'alert-2',
    text: '3 văn bản đến',
    emphasis: true,
    suffix: 'quá hạn cần xem ngay',
  },
  {
    id: 'alert-3',
    text: 'Nguyễn Văn Minh đang',
    emphasis: false,
    suffix: 'chậm tiến độ dự án API',
    suffixEmphasis: true,
  },
];

export const dataDashboardMediumStats = [
  {
    id: 'team-performance',
    color: 'navy',
    value: '78',
    suffix: '%',
    subText: 'Hiệu suất đội nhóm · Mục tiêu 85%',
    trend: { type: 'down', text: '7% dưới mục tiêu' },
    footerStats: [
      { id: 'on-time', color: 'green', text: '9 đúng hạn' },
      { id: 'delayed', color: 'red', text: '2 chậm tiến độ' },
    ],
  },
  {
    id: 'approvals-waiting',
    color: 'orange',
    value: '7',
    subText: 'Chờ phê duyệt · TB 2.3 ngày/yêu cầu',
    chips: [
      { id: 'doc', label: '3 Văn bản', color: 'default' },
      { id: 'task', label: '2 Công việc', color: 'orange' },
      { id: 'car', label: '1 Đặt xe', color: 'navy' },
      { id: 'passport', label: '1 Hộ chiếu', color: 'yellow' },
    ],
  },
  {
    id: 'tasks-room',
    color: 'teal',
    value: '34',
    subText: 'Công việc phòng · ▲ 19% so tháng trước',
    chips: [
      { id: 'doing', label: '15 Đang làm', color: 'default' },
      { id: 'overdue', label: '4 Quá hạn', color: 'orange' },
      { id: 'done', label: '17 Hoàn thành', color: 'green' },
    ],
  },
  {
    id: 'documents-month',
    color: 'green',
    value: '41',
    subText: 'Văn bản tháng này · Đã xử lý 87%',
    chips: [
      { id: 'doc-overdue', label: '3 Quá hạn', color: 'red' },
      { id: 'doc-pending', label: '5 Chờ duyệt', color: 'orange' },
      { id: 'doc-done', label: '33 Đã xong', color: 'green' },
    ],
  },
];

export const dataDashboardMediumEmployeeStatus = {
  tabs: [
    { id: 'chiso', label: 'Chỉ số phòng' },
    { id: 'dang', label: 'Đang thực hiện', badge: { value: 9, color: 'teal' } },
    { id: 'sap', label: 'Sắp đến hạn', badge: { value: 3, color: 'orange' } },
    { id: 'cham', label: 'Chậm tiến độ', badge: { value: 2, color: 'red' } },
  ],
  stackedBar: {
    title: 'CÔNG VIỆC THEO TRẠNG THÁI',
    segments: [
      {
        id: 'doing',
        label: 'Đang thực hiện',
        value: 9,
        width: 64.3,
        color: 'teal',
      },
      {
        id: 'near-deadline',
        label: 'Sắp đến hạn',
        value: 3,
        width: 21.4,
        color: 'orange',
      },
      {
        id: 'late',
        label: 'Chậm tiến độ',
        value: 2,
        width: 14.3,
        color: 'red',
      },
    ],
  },
  bigStats: [
    {
      id: 'on-time',
      value: '78%',
      color: 'teal',
      label: 'HT ĐÚNG HẠN',
      subLabel: 'Mục tiêu 85%',
    },
    {
      id: 'done',
      value: '12',
      color: 'navy',
      label: 'CV XONG',
      subLabel: '/ 34 tổng',
    },
    {
      id: 'docs',
      value: '87%',
      color: 'orange',
      label: 'VB XỬ LÝ',
      subLabel: '36 / 41',
    },
  ],
  resourceTitle: 'PHÂN BỔ NGUỒN LỰC',
  resourceRows: [
    { id: 'hao', name: 'Lê Văn Hào', percent: 83, color: 'green' },
    { id: 'lan', name: 'Trần Thị Lan', percent: 88, color: 'teal' },
    { id: 'khoa', name: 'Bùi Minh Khoa', percent: 72, color: 'teal' },
    { id: 'thu', name: 'Phạm Thị Thu', percent: 60, color: 'orange' },
    { id: 'minh', name: 'Nguyễn Văn Minh', percent: 95, color: 'red' },
    { id: 'nhung', name: 'Hoàng Thị Nhung', percent: 65, color: 'teal' },
  ],
  activeRows: [
    {
      id: 'act-hao',
      initials: 'LH',
      avatarColor: 'blue',
      name: 'Lê Văn Hào',
      role: 'Senior Dev',
      task: 'Module Quản lý tàu v2',
      progress: 87,
      progressColor: 'green',
      statusText: 'Đang xử lý',
      statusType: 'ok',
    },
    {
      id: 'act-thu',
      initials: 'PT',
      avatarColor: 'cyan',
      name: 'Phạm Thị Thu',
      role: 'BA',
      task: 'Đặc tả hệ thống văn bản',
      progress: 78,
      progressColor: 'teal',
      statusText: 'Đang xử lý',
      statusType: 'ok',
    },
    {
      id: 'act-lan',
      initials: 'TL',
      avatarColor: 'purple',
      name: 'Trần Thị Lan',
      role: 'Dev',
      task: 'Test Dashboard NV v1',
      progress: 96,
      progressColor: 'teal',
      statusText: 'Đang xử lý',
      statusType: 'ok',
    },
    {
      id: 'act-nhung',
      initials: 'HN',
      avatarColor: 'pink',
      name: 'Hoàng Thị Nhung',
      role: 'Designer',
      task: 'UI Kit Design System V2',
      progress: 77,
      progressColor: 'teal',
      statusText: 'Đang xử lý',
      statusType: 'ok',
    },
    {
      id: 'act-khoa',
      initials: 'BK',
      avatarColor: 'emerald',
      name: 'Bùi Minh Khoa',
      role: 'DevOps',
      task: 'Triển khai K8s staging',
      progress: 82,
      progressColor: 'green',
      statusText: 'Đang xử lý',
      statusType: 'ok',
    },
  ],
  upcomingRows: [
    {
      id: 'up-thu',
      initials: 'PT',
      avatarColor: 'cyan',
      name: 'Phạm Thị Thu',
      role: 'BA',
      task: 'Đặc tả hệ thống văn bản',
      progress: 60,
      progressColor: 'orange',
      statusText: 'Còn 2 ngày',
      statusType: 'warn',
    },
    {
      id: 'up-khoa',
      initials: 'BK',
      avatarColor: 'emerald',
      name: 'Bùi Minh Khoa',
      role: 'DevOps',
      task: 'Triển khai K8s production',
      progress: 72,
      progressColor: 'orange',
      statusText: 'Còn 3 ngày',
      statusType: 'warn',
    },
    {
      id: 'up-minh',
      initials: 'VM',
      avatarColor: 'amber',
      name: 'Nguyễn Văn Minh',
      role: 'Dev',
      task: 'API Tích hợp cổng TT',
      progress: 35,
      progressColor: 'orange',
      statusText: 'Còn 5 ngày',
      statusType: 'warn',
    },
  ],
  delayedRows: [
    {
      id: 'late-minh',
      initials: 'VM',
      avatarColor: 'amber',
      name: 'Nguyễn Văn Minh',
      role: 'Dev',
      task: 'API Tích hợp cổng TT',
      progress: 35,
      progressColor: 'red',
      statusText: 'Chậm 5 ngày',
      statusType: 'late',
    },
    {
      id: 'late-thu',
      initials: 'PT',
      avatarColor: 'cyan',
      name: 'Phạm Thị Thu',
      role: 'BA',
      task: 'Đặc tả hệ thống văn bản',
      progress: 60,
      progressColor: 'orange',
      statusText: 'Chậm 2 ngày',
      statusType: 'late',
    },
  ],
};

export const dataDashboardMediumApprovals = {
  total: 7,
  summary: [
    {
      id: 'in-time',
      label: 'Trong hạn',
      value: 3,
      percent: 43,
      color: 'green',
    },
    {
      id: 'near',
      label: 'Sắp đến hạn',
      value: 2,
      percent: 29,
      color: 'orange',
    },
    { id: 'over', label: 'Quá hạn', value: 2, percent: 29, color: 'red' },
  ],
  breakdownTitle: 'PHÂN LOẠI YÊU CẦU',
  breakdown: [
    {
      id: 'docs',
      icon: '📄',
      label: 'Văn bản',
      value: 3,
      percent: 43,
      color: 'navy',
    },
    {
      id: 'it',
      icon: '🖥️',
      label: 'CNTT',
      value: 2,
      percent: 29,
      color: 'teal',
    },
    {
      id: 'car',
      icon: '🚗',
      label: 'Đặt xe',
      value: 1,
      percent: 14,
      color: 'orange',
    },
    {
      id: 'training',
      icon: '🎓',
      label: 'Đào tạo',
      value: 1,
      percent: 14,
      color: 'purple',
    },
  ],
  list: [
    {
      id: 'apv-1',
      typeIcon: '📄',
      sender: 'Phạm Thị Thu',
      sentAt: '25/02',
      title: 'Công văn đi số 12/2026 – Xin chủ trương đầu tư cơ sở hạ tầng số',
      overdueText: 'Quá hạn 3 ngày',
      overdue: true,
      approveLabel: 'Ký duyệt',
    },
    {
      id: 'apv-2',
      typeIcon: '🖥️',
      sender: 'Trần Thị Nhung',
      sentAt: '26/02',
      title: 'Đề xuất nâng cấp server – Quý 2/2026 phục vụ hệ thống GLNS',
      approveLabel: 'Phê duyệt',
    },
    {
      id: 'apv-3',
      typeIcon: '🎓',
      sender: 'Nguyễn Thanh Phong',
      sentAt: '21/02',
      title: 'Kế hoạch đào tạo nhân lực CNTT 2026 – Chương trình nội bộ Q1',
      overdueText: 'Quá hạn 7 ngày',
      overdue: true,
      approveLabel: 'Phê duyệt',
    },
    {
      id: 'apv-4',
      typeIcon: '🚗',
      sender: 'Lê Văn Hào',
      sentAt: '28/02',
      title: 'Yêu cầu đặt xe đi công tác Hà Nội – 05/03/2026',
      approveLabel: 'Chấp nhận',
    },
  ],
};

export const dataDashboardMediumDocuments = {
  incoming: [
    {
      id: 'in-1',
      time: '08:38',
      title: 'Chỉ thị 03/2026/CT – TCSG về chuyển đổi số cảng biển thông minh',
      from: 'Từ: VP Tổng Công ty · Deadline: Hôm nay',
      tags: [{ id: 'urgent-1', label: 'THƯỢNG KHẨN', color: 'red-solid' }],
      certify: true,
    },
    {
      id: 'in-2',
      time: '07:15',
      title: 'Yêu cầu báo cáo nhân sự Q1/2026 toàn hệ thống',
      from: 'Từ: Phòng HCNS · Deadline: 28/02',
      tags: [{ id: 'urgent-2', label: 'KHẨN', color: 'red' }],
    },
    {
      id: 'in-3',
      time: '46p',
      title: 'Kế hoạch tập huấn AI 1.1 Quý 1 – Module NLP ứng dụng',
      from: 'Từ: Phòng ATTT · Deadline: 06/03',
      tags: [{ id: 'flash-1', label: 'HỎA TỐC', color: 'orange-solid' }],
      certify: true,
    },
    {
      id: 'in-4',
      time: '26/02',
      title: 'Thông báo họp tổng kết tháng 02/2026 và phương hướng Q2',
      from: 'Từ: Văn phòng Phòng · Họp 03/03',
      tags: [{ id: 'normal-1', label: 'THƯỜNG', color: 'normal' }],
    },
    {
      id: 'in-5',
      time: '24/02',
      title: 'Hướng dẫn quy trình nghiệm thu phần mềm nội bộ theo ISO',
      from: 'Từ: Phòng Tổng CT · Hiệu lực 21/03',
      tags: [{ id: 'normal-2', label: 'THƯỜNG', color: 'normal' }],
    },
    {
      id: 'in-6',
      time: '20/02',
      title: 'Thông báo cập nhật chính sách bảo mật dữ liệu nội bộ',
      from: 'Từ: Phòng ATTT · Tổng Công ty',
      tags: [{ id: 'normal-3', label: 'THƯỜNG', color: 'normal' }],
    },
  ],
  outgoing: [
    {
      id: 'out-1',
      time: 'Hôm nay',
      title: 'Báo cáo tiến độ dự án GLNS 2.0 – Tháng 02/2026',
      from: 'Gửi: Ban Giám Đốc · Trạng thái: Đã ban hành',
      tags: [{ id: 'published-1', label: 'ĐÃ BAN HÀNH', color: 'out' }],
    },
    {
      id: 'out-2',
      time: '27/02',
      title: 'Đề xuất bổ sung nguồn nhân lực phòng CNTT Q2/2026',
      from: 'Gửi: Phòng HCNS · Trạng thái: Dự thảo',
      tags: [{ id: 'draft-1', label: 'DỰ THẢO', color: 'warn' }],
    },
    {
      id: 'out-3',
      time: '25/02',
      title: 'Kế hoạch triển khai Digital Office Module văn bản',
      from: 'Gửi: Phòng Tổng CT · Trạng thái: Chờ duyệt',
      tags: [{ id: 'waiting-1', label: 'CHỜ DUYỆT', color: 'waiting' }],
    },
    {
      id: 'out-4',
      time: '22/02',
      title: 'Phản hồi về quy trình nghiệm thu phần mềm nội bộ',
      from: 'Gửi: VP Tổng Công ty · Trạng thái: Đã ban hành',
      tags: [{ id: 'published-2', label: 'ĐÃ BAN HÀNH', color: 'out' }],
    },
    {
      id: 'out-5',
      time: '18/02',
      title: 'Báo cáo kiểm tra an ninh mạng tháng 02/2026',
      from: 'Gửi: Phòng ATTT · Trạng thái: Dự thảo',
      tags: [{ id: 'draft-2', label: 'DỰ THẢO', color: 'warn' }],
    },
    {
      id: 'out-6',
      time: '12/02',
      title: 'Đề xuất quy trình xử lý sự cố hệ thống GLNS khẩn cấp',
      from: 'Gửi: BGĐ Kỹ thuật · Trạng thái: Chờ duyệt',
      tags: [{ id: 'waiting-2', label: 'CHỜ DUYỆT', color: 'waiting' }],
    },
  ],
};

export const dataDashboardMediumHeatmap = {
  days: ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN'],
  values: [
    [40, 65, 80, 55, 30, 15, 5],
    [75, 90, 60, 85, 45, 28, 10],
    [50, 70, 95, 40, 65, 50, 18],
    [85, 55, 75, 100, 70, 35, 22],
  ],
};

export const dataDashboardMediumProjects = [
  {
    id: 'proj-1',
    name: 'Hệ thống GLNS 2.0',
    statusType: 'ok',
    statusText: 'Đúng hạn',
    dateRange: '📅 15/01 – 30/06',
    membersText: '👤 9 người',
    memberHighlight: '(3 cán bộ)',
    progress: 72,
    progressColor: 'teal',
  },
  {
    id: 'proj-2',
    name: 'API Tích hợp Cổng thông tin',
    statusType: 'ok',
    statusText: 'Đúng hạn',
    dateRange: '📅 10/02 – 15/03',
    membersText: '👤 3 người',
    memberHighlight: '(2 cán bộ)',
    progress: 35,
    progressColor: 'teal',
  },
  {
    id: 'proj-3',
    name: 'Digital Office Module Văn bản',
    statusType: 'late',
    statusText: 'Quá hạn',
    dateRange: '📅 01/02 – 01/04',
    membersText: '👤 2 người',
    memberHighlight: '(2 cán bộ)',
    progress: 58,
    progressColor: 'red',
  },
];

export const dataDashboardMediumMeetings = [
  {
    id: 'today',
    separator: 'HÔM NAY, 28/02',
    items: [
      {
        id: 'mtg-1',
        time: '09:00',
        dayLabel: 'Hôm nay',
        blockColor: 'red',
        title: 'Họp tiến độ nhóm phát triển',
        meta: '📍 Phòng A2 · ⏱ 1 giờ · 👥 8 người',
        actionType: 'join',
        actionLabel: 'Tham gia',
        note: '⚡ Còn 30 phút',
        noteColor: 'red',
      },
      {
        id: 'mtg-2',
        time: '14:00',
        dayLabel: 'Hôm nay',
        blockColor: 'navy',
        title: 'Review UI Dashboard TCSG',
        meta: '💻 Teams · ⏱ 2 giờ · 👥 5 người',
        actionType: 'join',
        actionLabel: 'Tham gia',
      },
    ],
  },
  {
    id: 'tuesday',
    separator: 'THỨ BA, 03/03',
    items: [
      {
        id: 'mtg-3',
        time: '18:00',
        dayLabel: '03/03',
        blockColor: 'teal',
        title: 'Báo cáo Q1 với Ban Giám Đốc',
        meta: '🏢 Hội trường · ⏱ 3 giờ',
        actionType: 'respond',
        actionLabel: 'Xác nhận',
        secondaryActionLabel: 'Từ chối',
      },
    ],
  },
  {
    id: 'wednesday',
    separator: 'THỨ TƯ, 04/03',
    items: [
      {
        id: 'mtg-4',
        time: '10:00',
        dayLabel: '04/03',
        blockColor: 'blue',
        title: 'Họp triển khai GLNS 2.0 module mới',
        meta: '💻 Teams · ⏱ 1.5 giờ · 👥 6 người',
        actionType: 'respond',
        actionLabel: 'Xác nhận',
        secondaryActionLabel: 'Từ chối',
      },
    ],
  },
];

export const dataDashboardMediumUpcomingEvents = [
  {
    id: 'ev-1',
    day: '05',
    month: 'THG 3',
    color: 'red',
    title: 'Hội nghị người lao động 2026',
    time: '14:00 – 17:00',
    location: 'Hội trường lớn',
  },
  {
    id: 'ev-2',
    day: '10',
    month: 'THG 3',
    color: 'teal',
    title: 'Workshop Chuyển đổi số Q1',
    time: '09:00 – 17:00',
    location: 'Zoom',
  },
  {
    id: 'ev-3',
    day: '15',
    month: 'THG 3',
    color: 'orange',
    title: 'Đào tạo An toàn thông tin',
    time: '08:00 – 12:00',
    location: 'Phòng đào tạo',
  },
  {
    id: 'ev-1',
    day: '05',
    month: 'THG 3',
    color: 'red',
    title: 'Hội nghị người lao động 2026',
    time: '14:00 – 17:00',
    location: 'Hội trường lớn',
  },
  {
    id: 'ev-2',
    day: '10',
    month: 'THG 3',
    color: 'teal',
    title: 'Workshop Chuyển đổi số Q1',
    time: '09:00 – 17:00',
    location: 'Zoom',
  },
  {
    id: 'ev-3',
    day: '15',
    month: 'THG 3',
    color: 'orange',
    title: 'Đào tạo An toàn thông tin',
    time: '08:00 – 12:00',
    location: 'Phòng đào tạo',
  },
  {
    id: 'ev-1',
    day: '05',
    month: 'THG 3',
    color: 'red',
    title: 'Hội nghị người lao động 2026',
    time: '14:00 – 17:00',
    location: 'Hội trường lớn',
  },
  {
    id: 'ev-2',
    day: '10',
    month: 'THG 3',
    color: 'teal',
    title: 'Workshop Chuyển đổi số Q1',
    time: '09:00 – 17:00',
    location: 'Zoom',
  },
  {
    id: 'ev-3',
    day: '15',
    month: 'THG 3',
    color: 'orange',
    title: 'Đào tạo An toàn thông tin',
    time: '08:00 – 12:00',
    location: 'Phòng đào tạo',
  },
];

export const dataDashboardMediumUtilityRequests = {
  actions: [
    {
      id: 'car',
      icon: '🚗',
      label: 'Đặt xe',
      badge: { value: 2, color: 'orange' },
    },
    {
      id: 'passport',
      icon: '🛂',
      label: 'Hộ chiếu',
      badge: { value: 1, color: 'green' },
    },
    {
      id: 'feedback',
      icon: '📣',
      label: 'Phản ánh',
      badge: { value: 3, color: 'orange' },
    },
  ],
  statsTitle: 'THỐNG KÊ THÁNG NÀY',
  stats: [
    {
      id: 'car-stat',
      label: '🚗 Tổng yêu cầu / Đã duyệt',
      values: [
        { text: '8', color: 'navy' },
        { text: '5', color: 'green' },
      ],
    },
    {
      id: 'passport-stat',
      label: '🛂 Tổng yêu cầu / Đã làm',
      values: [
        { text: '4', color: 'navy' },
        { text: '3', color: 'teal' },
      ],
    },
    {
      id: 'feedback-stat',
      label: '📣 Đã giải quyết / Đang chờ',
      values: [
        { text: '7', color: 'orange' },
        { text: '3', color: 'red' },
      ],
    },
  ],
};

export const dataDashboardMediumNews = [
  {
    id: 'news-1',
    icon: '🏆',
    title: 'TCSG đạt giải "Doanh nghiệp Logistics xuất sắc 2025"',
    reactions: ['❤️ 214', '👁 328', '💬 56'],
    date: '05/02',
  },
  {
    id: 'news-2',
    icon: '🎁',
    title: 'Chương trình phúc lợi mới cho CBNV Tân Cảng 2026',
    reactions: ['❤️ 189', '👁 412', '💬 89'],
    date: '01/02',
  },
  {
    id: 'news-3',
    icon: '🚀',
    title: 'Ra mắt hệ thống Digital Office phiên bản 2.0',
    reactions: ['❤️ 305', '👁 567', '💬 124'],
    date: '28/01',
  },
  {
    id: 'news-4',
    icon: '📚',
    title: 'Hướng dẫn đăng ký học bổng nâng cao kỹ năng 2026',
    reactions: ['❤️ 97', '👁 201', '💬 34'],
    date: '22/01',
  },
  
  {
    id: 'news-1',
    icon: '🏆',
    title: 'TCSG đạt giải "Doanh nghiệp Logistics xuất sắc 2025"',
    reactions: ['❤️ 214', '👁 328', '💬 56'],
    date: '05/02',
  },
  {
    id: 'news-2',
    icon: '🎁',
    title: 'Chương trình phúc lợi mới cho CBNV Tân Cảng 2026',
    reactions: ['❤️ 189', '👁 412', '💬 89'],
    date: '01/02',
  },
  {
    id: 'news-3',
    icon: '🚀',
    title: 'Ra mắt hệ thống Digital Office phiên bản 2.0',
    reactions: ['❤️ 305', '👁 567', '💬 124'],
    date: '28/01',
  },
  {
    id: 'news-4',
    icon: '📚',
    title: 'Hướng dẫn đăng ký học bổng nâng cao kỹ năng 2026',
    reactions: ['❤️ 97', '👁 201', '💬 34'],
    date: '22/01',
  },
];
