// const APP_BASE = 'https://camunda-bpmn.lifetex.vn'
const APP_BASE = 'http://192.168.0.214:4146'


export const CREATE_DEPLOYMENT_POST = `${APP_BASE}/engine-rest/deployment/create`
export const IMPORT_DEPLOYMENT = `${APP_BASE}/bpmn/diagram.bpmn`;

export function customTranslate(template, replacements) {
    const translations = {
        'Activate hand tool': 'Kích hoạt công cụ tay',
        'Activate lasso tool': 'Kích hoạt công cụ chọn vùng',
        'Activate create/remove space tool': 'Tạo hoặc xóa không gian',
        'Activate global connect tool': 'Kết nối toàn cục',
        'Create start event': 'Tạo sự kiện bắt đầu',
        'Create intermediate/boundary event': 'Tạo sự kiện trung gian / ràng buộc',
        'Create end event': 'Tạo sự kiện kết thúc',
        'Create gateway': 'Tạo cổng điều kiện',
        'Create task': 'Tạo công việc',
        'Create data object reference': 'Tạo đối tượng dữ liệu',
        'Create data store reference': 'Tạo kho dữ liệu',
        'Create expanded sub-process': 'Tạo quy trình con mở rộng',
        'Create pool/participant': 'Tạo bể hoặc người tham gia',
        'Create group': 'Tạo nhóm',
        'Append end event': 'Nối sự kiện kết thúc',
        'Append gateway': 'Nối điều kiện',
        'Append task': 'Nối công việc',
        'Append intermediate/boundary event': 'Thêm sự kiện trung gian/ranh giới',
        'Add text annotation': 'Thêm văn bản chú thích',
        'Change element': 'Thay đổi phần tử',
        'Delete': 'Xóa',
        'Connect to other element': 'Kết nối đến phần tử khác',
        'Parallel multi-instance': 'Lặp song song',
        'Sequential multi-instance': 'Lặp tuần tự',
        'Loop': 'Lặp',
        'User task': 'Tác vụ người dùng (người thực hiện bằng tay trên hệ thống)',
        'Service task': 'Tác vụ dịch vụ (do hệ thống hoặc API tự động xử lý)',
        'Send task': 'Tác vụ gửi (gửi thông điệp hoặc dữ liệu ra ngoài)',
        'Receive task': 'Tác vụ nhận (nhận thông điệp hoặc dữ liệu từ bên ngoài)',
        'Manual task': 'Tác vụ thủ công (thực hiện ngoài hệ thống, ví dụ ký giấy)',
        'Business rule task': 'Tác vụ quy tắc nghiệp vụ (thực thi rule engine, decision table)',
        'Script task': 'Tác vụ script (chạy đoạn mã script tự động)',
        'Call activity': 'Hoạt động gọi (gọi một quy trình hoặc tác vụ khác)',
        'Sub-process (collapsed)': 'Quy trình con (đóng lại)',
        'Sub-process (expanded)': 'Quy trình con (mở rộng)',
        'Ad-hoc sub-process (collapsed)': 'Quy trình con tùy biến (đóng lại)',
        'Ad-hoc sub-process (expanded)': 'Quy trình con tùy biến (mở rộng)',
        'Intermediate throw event': 'Sự kiện trung gian (phát ra)',
        'End event': 'Sự kiện kết thúc',
        'Message start event': 'Sự kiện bắt đầu (theo tin nhắn)',
        'Timer start event': 'Sự kiện bắt đầu (theo thời gian)',
        'Conditional start event': 'Sự kiện bắt đầu (theo điều kiện)',
        'Signal start event': 'Sự kiện bắt đầu (theo tín hiệu)',
        'Start event': 'Sự kiện bắt đầu',
        'Message end event': 'Sự kiện kết thúc (theo tin nhắn)',
        'Escalation end event': 'Sự kiện kết thúc (theo leo thang)',
        'Error end event': 'Sự kiện kết thúc (theo lỗi)',
        'Compensation end event': 'Sự kiện kết thúc (theo bồi hoàn)',
        'Signal end event': 'Sự kiện kết thúc (theo tín hiệu)',
        'Terminate end event': 'Sự kiện kết thúc (chấm dứt toàn bộ)',
        'Message intermediate catch event': 'Sự kiện trung gian (bắt tin nhắn)',
        'Message intermediate throw event': 'Sự kiện trung gian (phát tin nhắn)',
        'Timer intermediate catch event': 'Sự kiện trung gian (bắt thời gian)',
        'Escalation intermediate throw event': 'Sự kiện trung gian (phát leo thang)',
        'Conditional intermediate catch event': 'Sự kiện trung gian (bắt điều kiện)',
        'Link intermediate catch event': 'Sự kiện trung gian (bắt liên kết)',
        'Link intermediate throw event': 'Sự kiện trung gian (phát liên kết)',
        'Compensation intermediate throw event': 'Sự kiện trung gian (phát bồi hoàn)',
        'Signal intermediate catch event': 'Sự kiện trung gian (bắt tín hiệu)',
        'Signal intermediate throw event': 'Sự kiện trung gian (phát tín hiệu)',
        'Parallel gateway': 'Điều kiện song song',
        'Inclusive gateway': 'Điều kiện bao gồm',
        'Complex gateway': 'Điều kiện phức hợp',
        'Event-based gateway': 'Điều kiện dựa trên sự kiện',
        'Data store reference': 'Tham chiếu kho dữ liệu',
        'Data object reference': 'Tham chiếu đối tượng dữ liệu',
        'Transaction': 'Giao dịch',
        'Event sub-process': 'Tiến trình con theo sự kiện',
        'Ad-hoc sub-process': 'Tiến trình con tự do',
        'Sub Process': 'Quy trình con',
        'Expanded Sub Process': 'Quy trình con mở rộng',
        'Collapsed Sub Process': 'Quy trình con thu gọn',
        'Activity': 'Hoạt động',
        'Task': 'Tác vụ',
        'User Task': 'Tác vụ người dùng',
        'Service Task': 'Tác vụ dịch vụ',
        'Script Task': 'Tác vụ script',
        'Manual Task': 'Tác vụ thủ công',
        'Business Rule Task': 'Tác vụ quy tắc nghiệp vụ',
        'Send Task': 'Tác vụ gửi',
        'Receive Task': 'Tác vụ nhận',
        'Start Event': 'Sự kiện bắt đầu',
        'End Event': 'Sự kiện kết thúc',
        'Intermediate Event': 'Sự kiện trung gian',
        'Gateway': 'Cổng',
        'Exclusive Gateway': 'Cổng độc quyền',
        'Parallel Gateway': 'Cổng song song',
        'Inclusive Gateway': 'Cổng bao gồm',
        'Event Gateway': 'Cổng sự kiện',
        'Sequence Flow': 'Luồng tuần tự',
        'Message Flow': 'Luồng tin nhắn',
        'Association': 'Liên kết',
        'Data Object': 'Đối tượng dữ liệu',
        'Data Store': 'Kho dữ liệu',
        'Pool': 'Bể',
        'Lane': 'Làn',
        'Text Annotation': 'Chú thích văn bản',
        'Group': 'Nhóm',
        'Process': 'Quy trình'
    }
    let text = translations[template] || template;

    if (replacements) {
        Object.keys(replacements).forEach((key) => {
            text = text.replace(new RegExp(`{${key}}`, "g"), replacements[key]);
        });
    }

    return text;
}

export const mapKey = {
  text: 'string',
  number: 'long',
  date: 'date',
  file: 'string',
  checkbox: 'string',
  autocomplete: 'string',
  enum: 'string',
  radio: 'string',
  extractUser: 'string',
  nextHandlers: 'string',
}