/**
 * Fake data danh sách Người mượn (thay thế HRM sau này)
 * Dùng cho dropdown "Người mượn" trong form tạo yêu cầu mượn HC cá nhân
 */
export const fakeBorrowerData = [
    {
        id: 'BR001',
        employeeNumber: 'NV10001',
        nameVn: 'Nguyễn Văn An',
        email: 'nguyen.van.an@tcsg.vn',
        position: 'Chuyên viên',
        rank: 'Đại úy',
        unit: 'Phòng Kế hoạch',
        department: 'Ban Kế hoạch - Đầu tư',
        leaderId: 'LD001',
    },
    {
        id: 'BR002',
        employeeNumber: 'NV10002',
        nameVn: 'Trần Thị Bích',
        email: 'tran.thi.bich@tcsg.vn',
        position: 'Chuyên viên',
        rank: 'Thượng úy',
        unit: 'Phòng Tổ chức',
        department: 'Ban Tổ chức - Nhân sự',
        leaderId: 'LD002',
    },
    {
        id: 'BR003',
        employeeNumber: 'NV10003',
        nameVn: 'Lê Hoàng Cường',
        email: 'le.hoang.cuong@tcsg.vn',
        position: 'Phó phòng',
        rank: 'Thiếu tá',
        unit: 'Phòng CNTT',
        department: 'Ban Công nghệ thông tin',
        leaderId: 'LD003',
    },
    {
        id: 'BR004',
        employeeNumber: 'NV10004',
        nameVn: 'Phạm Minh Đức',
        email: 'pham.minh.duc@tcsg.vn',
        position: 'Chuyên viên',
        rank: 'Đại úy',
        unit: 'Phòng Tài chính',
        department: 'Ban Tài chính - Kế toán',
        leaderId: 'LD001',
    },
    {
        id: 'BR005',
        employeeNumber: 'NV10005',
        nameVn: 'Hoàng Thị Hà',
        email: 'hoang.thi.ha@tcsg.vn',
        position: 'Chuyên viên',
        rank: 'Trung úy',
        unit: 'Phòng Hành chính',
        department: 'Văn phòng',
        leaderId: 'LD004',
    },
    {
        id: 'BR006',
        employeeNumber: 'NV10006',
        nameVn: 'Vũ Đức Giang',
        email: 'vu.duc.giang@tcsg.vn',
        position: 'Trưởng phòng',
        rank: 'Trung tá',
        unit: 'Phòng Khai thác',
        department: 'Ban Khai thác',
        leaderId: 'LD002',
    },
    {
        id: 'BR007',
        employeeNumber: 'NV10007',
        nameVn: 'Đặng Văn Hùng',
        email: 'dang.van.hung@tcsg.vn',
        position: 'Chuyên viên',
        rank: 'Đại úy',
        unit: 'Phòng Kế hoạch',
        department: 'Ban Kế hoạch - Đầu tư',
        leaderId: 'LD001',
    },
    {
        id: 'BR008',
        employeeNumber: 'NV10008',
        nameVn: 'Ngô Thanh Lan',
        email: 'ngo.thanh.lan@tcsg.vn',
        position: 'Phó phòng',
        rank: 'Thiếu tá',
        unit: 'Phòng Tổ chức',
        department: 'Ban Tổ chức - Nhân sự',
        leaderId: 'LD002',
    },
    {
        id: 'BR009',
        employeeNumber: 'NV10009',
        nameVn: 'Bùi Quốc Minh',
        email: 'bui.quoc.minh@tcsg.vn',
        position: 'Chuyên viên',
        rank: 'Thượng úy',
        unit: 'Phòng CNTT',
        department: 'Ban Công nghệ thông tin',
        leaderId: 'LD003',
    },
    {
        id: 'BR010',
        employeeNumber: 'NV10010',
        nameVn: 'Lý Thị Ngọc',
        email: 'ly.thi.ngoc@tcsg.vn',
        position: 'Chuyên viên',
        rank: 'Trung úy',
        unit: 'Phòng Hành chính',
        department: 'Văn phòng',
        leaderId: 'LD004',
    },
];
